version: '3'

services:
  dash-plotly-app:
    build:
      context: ./visualization
    restart: always
 #   volumes:
#      - "./visualization:/asteroid_data_processing"

  dash-api-app:
    build:
      context: ./processing
    restart: always
  #  volumes:
   #   - "./processing:/asteroid_data_processing"
  nginx:
      build:
        context: ./nginx
      ports:
        - "80:80"
      depends_on:
        - dash-plotly-app
        - dash-api-app
      command: ["nginx", "-g", "daemon off;"]