version: '3'

services:
  dash-plotly-app:
    build:
      context: ./visualization
    restart: always
    image: your-dockerid/yourimage

  dash-api-app:
    build:
      context: ./processing
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash-plotly-app
      - dash-api-app
    command: ["nginx", "-g", "daemon off;"]