version: '3'

services:
  dash-plotly-app:
    build:
      context: ./visualization
    ports:
      - "8050:8050"
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8050", "asteroid_visualization:server"]

  dash-api-app:
    build:
      context: ./processing
    ports:
      - "5000"
  nginx:
      build:
        context: ./nginx
      ports:
        - "80:80"
      depends_on:
        - dash-plotly-app
        - dash-api-app
      command: ["nginx", "-g", "daemon off;"]